admin/urls.py
from django.conf.urls import url
from django.urls import path
from .views import auto_update, index
app_name = 'admin'

urlpatterns = [
    url(r'^$', index.index),
    path(r'get_config', auto_update.get_config, name='get_config'),
    path(r'set_auto_update', auto_update.set_auto_update, name='set_auto_update'),
    url(r'finished', auto_update.finished),
    url(r'del_cf_users', index.del_cf_users),
    url(r'list_add', index.list_add),
    url(r'list_override', index.list_override),


]

board/urls.py
from django.urls import path
from .views import board_rating
from .views import board_rating_change

app_name = 'board'

urlpatterns = [
    path('', board_rating),
    path('<int:board_id>/', board_rating, name='board_view'),
    path('profile/<str:handle>/', board_rating_change, name='user_profile'),
]

logsystem/urls.py
from django.conf.urls import url, include
from django.urls import path
from logreg.views import index, send_captcha, user_check, user_exist, password_check, reset_password_captcha, receive_captcha
urlpatterns = [
    url(r'^board/', include('board.urls')),
    url(r'^logreg/', include('logreg.urls')),
    url(r'^logreg/', include('django.contrib.auth.urls')),
    url(r'^interfaces/', include('interfaces.urls')),
    url(r'^$', index, name='index'),
    url(r'^admin/', include('superuser.urls')),
    url(r'^ajax/send_captcha/', send_captcha, name='send_captcha'),
    url(r'^ajax/user_check', user_check, name='user_check'),
    url(r'^ajax/user_exist', user_exist, name='user_exist'),
    url(r'^ajax/password_check', password_check, name='password_check'),
    url(r'^ajax/reset_password_captcha/', reset_password_captcha),
    path('verify/<str:captcha>', receive_captcha),
]

board/models.py
from django.db import models
from logreg.models import User
from django.conf import settings


class CFUser(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    handle = models.CharField(max_length=30, unique=True)
    rating = models.IntegerField(default=0)
    last_update = models.DateTimeField(auto_now=True)
    realname = models.CharField(max_length=5, default='')
    grade = models.IntegerField(default=0, blank=True)


class RatingChange(models.Model):
    newRating = models.IntegerField()
    ratingUpdateTimeSeconds = models.IntegerField(primary_key=True)
    cf_user = models.ForeignKey(CFUser, on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'board_ratingchange'
        unique_together = (('cf_user', 'ratingUpdateTimeSeconds'),)


class Board(models.Model):
    name = models.CharField(max_length=20)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    type = models.CharField(max_length=20)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)


class BoardItem(models.Model):
    cf_user = models.ForeignKey(CFUser, on_delete=models.PROTECT)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    max_rating = models.IntegerField()
    old_rating = models.IntegerField()
    last_update = models.DateTimeField(auto_now=True)
    times = models.IntegerField(default=0)

board/views.py
from django.shortcuts import render
from board.models import RatingChange
from board.models import Board, BoardItem


# 榜单列表
def board_list():
    List = []
    for item in Board.objects.all():
        board = {'id': item.id, 'name': item.name, 'type': item.type, 'start_time': item.start_time,
                 'end_time': item.end_time}
        List.append(board)
    return List


# 查询榜是否存在
def board_exist(_id=-1):
    if Board.objects.filter(id=_id).exists():
        return True
    return False


def board_rating_operate(board_id=-1):
    class User(object):
        rank = rating = handle = oldRating = newRating = change = grade = times = 0
        nickname = realname = ''

        def keys(self):
            return ('rank', 'rating', 'handle', 'oldRating', 'newRating', 'change', 'nickname', 'realname')

        def __getitem__(self, item):
            return getattr(self, item)

    class User2(object):
        rank = rating = handle = grade = times = 0
        nickname = realname = ''

        def keys(self):
            return ('rank', 'rating', 'handle', 'nickname', 'realname')

        def __getitem__(self, item):
            return getattr(self, item)

    users = []
    if str("rating") == str(Board.objects.filter(id=board_id).get().type) or str(
            Board.objects.filter(id=board_id).get().type) == 'max_three':
        for item in BoardItem.objects.filter(board=Board.objects.filter(id=board_id).get()):
            info = User2()
            info.rating = item.max_rating
            info.handle = item.cf_user.handle
            info.realname = item.cf_user.realname
            info.grade = item.cf_user.grade
            if item.cf_user.user and item.cf_user.user.nickname:
                info.nickname = '(' + item.cf_user.user.nickname + ')'
            info.times = item.times
            users.append(info)
        users.sort(key=lambda x: x.rating, reverse=True)
        for i in range(len(users)):
            users[i].rank = i + 1
        return users
    else:
        for item in BoardItem.objects.filter(board=Board.objects.filter(id=board_id).get()):
            user = User()
            user.change = item.max_rating - item.old_rating
            if user.change <= 0:
                continue
            user.handle = item.cf_user.handle
            user.oldRating = item.old_rating
            user.newRating = item.max_rating
            user.realname = item.cf_user.realname
            user.times = item.times
            user.grade = item.cf_user.grade
            if item.cf_user.user and item.cf_user.user.nickname != '':
                user.nickname = '(' + item.cf_user.user.nickname + ')'
            users.append(user)
        users.sort(key=lambda x: x.change, reverse=True)
        for i in range(len(users)):
            users[i].rank = i + 1
            users[i].change = '+' + str(users[i].change)
        return users


def board_rating(request, board_id=-1):
    if not request.user.is_authenticated:
        return render(request, 'index.html')
    if board_id == -1:
        board_id = Board.objects.order_by('id').first().id
    time = Board.objects.filter(id=board_id).get().name
    creator = str(Board.objects.filter(id=board_id).get().creator)
    users = board_rating_operate(board_id)
    if str("rating") == str(Board.objects.filter(id=board_id).get().type) or str(Board.objects.filter(id=board_id)
                                                                                 .get().type) == 'max_three':
        return render(request, 'board/board_rating.html',
                      {'users': users, 'time': time, 'boards': Board.objects.all(), 'creator': creator})
    else:
        return render(request, 'board/board_upgrade.html',
                      {'users': users, 'time': time, 'boards': Board.objects.all(), 'creator': creator})


def board_rating_change(request, handle):
    if request.user.is_authenticated:
        queryset = RatingChange.objects.filter(cf_user__handle=handle)
        data = []
        for change in queryset:
            data.append([change.ratingUpdateTimeSeconds * 1000, change.newRating])
        data = str(data)[1:-1]
        return render(request, 'board/rating_change.html', {'data': data, 'name': handle})
    else:
        return render(request, 'index.html')



board/templates/board/board.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block js %}
    <script src="{% static "/bootstrap/js/popper.min.js" %}"></script>
    <script src="{% static "/bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "/board/board.js" %}"></script>
    <script>
    $(document).ready(function () {
        $('.nav-link').removeClass('active')
        $('#nav-element2').addClass('active')
    })
    </script>
{% endblock %}
{% block index %}

    <div class="container">
        <div class="container">
            <h3 class="text-center">
                {% block title %}
                    分数排行榜
                {% endblock %}
            </h3>
            <h6 class="text-center" style="color: grey">
                榜单创建人:{{ creator }}
            </h6>
            <div class="row">
                <div class="col-auto mr-auto"></div>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        选择排行榜
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        {% for board in boards %}
                            <a class="dropdown-item" href='{% url 'board:board_view' board.id %}'>{{ board.name }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">名次</th>
                <th scope="col">年级</th>
                <th scope="col">姓名</th>
                <th scope="col">CF帐号</th>
                <th scope="col">分数</th>
                <th scope="col">场次</th>
                {% block col %}
                {% endblock %}
            </tr>
            </thead>
            <tbody>
            {% block content %}
            {% endblock %}
            </tbody>
        </table>
        <div>
{% endblock %}

board/templates/board/board_rating.html
{% extends 'board/board.html' %}
{% block title %}
    {{ time }}
{% endblock %}
{% block content %}
    {% for user in users %}
{#        {% if user.rating %}#}
            <tr>
                <th scope="row">{{ user.rank }}</th>
                <td>{{ user.grade }}</td>
                <td>{{ user.realname }}{{ user.nickname }}</td>
                <td>{{ user.handle }}</td>
                <td><span class="rating">{{ user.rating }}</span></td>
                <td>{{ user.times }}</td>
                {#            <td><a href="profile/{{ user.handle }}">查看分数变化曲线</a></td>#}
                <td><a href="{% url 'board:user_profile' user.handle %}">查看分数变化曲线</a></td>
            </tr>
{#        {% endif %}#}
    {% endfor %}
{% endblock %}

board/templates/board/board_upgrade.html
{% extends 'board/board.html' %}
{% block title %}
    {{ time }}
{% endblock %}
{% block col %}
    <th scope="col">增幅</th>
{% endblock %}
{% block content %}
    {% for user in users %}
        <tr>
            <th scope="row">{{ user.rank }}</th>
            <td>{{ user.grade }}</td>
            <td>{{ user.realname }}{{ user.nickname }}</td>
            <td>{{ user.handle }}</td>
            <td>
                <span class="oldRating">{{ user.oldRating }}</span>
                ->
                <span class="rating">{{ user.newRating }}</span>
            </td>
            <td>{{ user.change }}</td>
            <td><a href="{% url 'board:user_profile' user.handle %}">查看分数变化曲线</a></td>
        </tr>
    {% endfor %}
{% endblock %}

board/templates/board/handle_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>排行榜</title>
</head>
<body marginheight="0px" marginwidth="0px">
<table width="100%" height="950px" style="background-color: darkgrey; ">
    <tr>
        <td colspan="1" width="100%" height="10%">menu</td>
    </tr>
    <tr>
        <td width="100%" height="87%">
            <div style="overflow-x: auto; overflow-y: auto; width: 100%; height: 87%;">
                <table width="100%" cellspacing="0">
                    <p>导入成功的有：</p>
                    <ul>
                        {% for info in results %}
                            <li>handle: {{ info.handle }} 姓名: {{ info.realname }}</li>
                        {% endfor %}
                    </ul>
                    <p>导入失败的有：</p>
                    <ul>
                        {% for info in errors %}
                            <li>导入信息: {{ info.text }}</li>
                            <li>失败原因：{{ info.comment }}</li>
                        {% endfor %}
                    </ul>
                </table>
            </div>
        </td>
    </tr>
    <tr>
        <td width="100%" height="3%" align="center" style="color:snow">@{{ date }} Leon & Toshi</td>
    </tr>
</table>
</body>
</html>


board/templates/board/rating_change.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block index %}
    <div id="container" style="min-width: 100px; height: 700px;"></div>
    <script src="{% static "board/highcharts.js" %}"></script>
    <script>
        var chart = Highcharts.chart('container', {
            title: {
                useHTML: true,
                text: "<a href='http://www.codeforces.com/profile/{{ name }}'>{{ name }}</a>分数曲线"
            },
            xAxis: {
                type: 'datetime',
                minTickInterval: 1000 * 3600 * 24,
                dateTimeLabelFormats: {
                    day: '%Y-%m-%d',
                    month: '%y-%m',
                    year: '%Y'
                }
            },
            yAxis: {
                title: {
                    text: '分数'
                },
                tickPositioner: function () {
                    var all_positions = [0, 800, 1000, 1200, 1400, 1600, 1900, 2100, 2300, 2600]
                    var positions = []
                    for (var i = 1; i < all_positions.length - 1; i++) {
                        var pre = all_positions[i - 1]
                        var nxt = all_positions[i + 1]
                        var now = all_positions[i]
                        if (now < this.dataMax && nxt > this.dataMin ||
                            now > this.dataMin && pre < this.dataMax) {
                            positions.push(now)
                        }
                    }
                    return positions
                }
            },
            tooltip: {
                xDateFormat: '%Y-%m-%d'
            },
            series: [{
                name: 'rating',
                data: [{{ data }}],
                zones: [{
                    value: 1200,
                    color: '#808080'
                }, {
                    value: 1400,
                    color: '#008000'
                }, {
                    value: 1600,
                    color: '#03A89E'
                }, {
                    value: 1900,
                    color: '#0000ff'
                }, {
                    value: 2100,
                    color: '#a0a'
                }, {
                    value: 2300,
                    color: '#FF8C00'
                }, {
                    color: '#ff0000'
                }]

            }],

            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: false
                    }
                }
            }
        });
    </script>
{% endblock %}