admin/urls.py
from django.conf.urls import url
from django.urls import path
from .views import auto_update, index
app_name = 'admin'

urlpatterns = [
    url(r'^$', index.index),
    path(r'get_config', auto_update.get_config, name='get_config'),
    path(r'set_auto_update', auto_update.set_auto_update, name='set_auto_update'),
    url(r'finished', auto_update.finished),
    url(r'del_cf_users', index.del_cf_users),
    url(r'list_add', index.list_add),
    url(r'list_override', index.list_override),


]

logreg/urls.py
from django.conf.urls import url
from . import views

app_name = 'logreg'

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^reset_password/', views.reset_password, name='reset_password'),
    url(r'^modify_self/', views.modify_self, name='modify_self'),
]

logsystem/urls.py
from django.conf.urls import url, include
from django.urls import path
from logreg.views import index, send_captcha, user_check, user_exist, password_check, reset_password_captcha, receive_captcha
urlpatterns = [
    url(r'^board/', include('board.urls')),
    url(r'^logreg/', include('logreg.urls')),
    url(r'^logreg/', include('django.contrib.auth.urls')),
    url(r'^interfaces/', include('interfaces.urls')),
    url(r'^$', index, name='index'),
    url(r'^admin/', include('superuser.urls')),
    url(r'^ajax/send_captcha/', send_captcha, name='send_captcha'),
    url(r'^ajax/user_check', user_check, name='user_check'),
    url(r'^ajax/user_exist', user_exist, name='user_exist'),
    url(r'^ajax/password_check', password_check, name='password_check'),
    url(r'^ajax/reset_password_captcha/', reset_password_captcha),
    path('verify/<str:captcha>', receive_captcha),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-cmn-Hans">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
    {% endblock %}
    <title>
        {% block title %}
            SCAU-CF
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static "/bootstrap/css/bootstrap.min.css" %}">

</head>
<body>
<script src="{% static "/jquery-3.3.1.min.js" %}"></script>
{% block js %}
{% endblock %}
<ul class="nav nav-tabs">
    <a class="navbar-brand" href="/">SCAU-CF</a>
    <li class="nav-item">
        <a class="nav-link active" href="/">首页</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="nav-element2" href="/board">排行榜</a>
    </li>
    {% if user.is_superuser %}
        <li class="nav-item">
            <a class="nav-link" id="nav-element3" href="/admin">管理</a>
        </li>
    {% endif %}
    {% if user.is_authenticated %}
        <span class="navbar-text" , style="margin-left: auto"></span>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logreg:modify_self' %}">{{ user.username }}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'password_change' %}">修改密码</a>
        </li>
        <li class="nav-item" style="text-align: right">
            <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">退出</a>
        </li>
    {% else %}
        <li class="nav-item" , style="margin-left: auto">
            <a class="nav-link" href="/logreg/login">登录</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/logreg/register">注册</a>
        </li>
    {% endif %}
</ul>
{% block index %}
{% endblock %}
<footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">©2018-2020 Ben & Toshi</p>
</footer>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block index %}
    {% if user.is_authenticated %}
        <div class="container">
            <h3 class="font-weight-bold">欢迎你：<a class="font-italic" style="color: #005cbf">{{ user.username }}</a></h3>
            <div id="container" style="min-width: 100px; height: 700px;"></div>
            <script src="{% static "board/highcharts.js" %}"></script>
            <script>
                var chart = Highcharts.chart('container', {
                    credits: {
                        enabled: false
                    },
                    title: {
                        text: null
                    },
                    xAxis: {
                        type: 'datetime',
                        minTickInterval: 1000 * 3600 * 24,
                        dateTimeLabelFormats: {
                            day: '%Y-%m-%d',
                            month: '%y-%m',
                            year: '%Y'
                        }
                    },
                    yAxis: {
                        title: {
                            text: '分数'
                        },
                        tickPositioner: function () {
                            var all_positions = [0, 800, 1000, 1200, 1400, 1600, 1900, 2200, 2400]
                            var positions = []
                            for (var i = 1; i < all_positions.length - 1; i++) {
                                var pre = all_positions[i - 1]
                                var nxt = all_positions[i + 1]
                                var now = all_positions[i]
                                if (now < this.dataMax && nxt > this.dataMin ||
                                    now > this.dataMin && pre < this.dataMax) {
                                    positions.push(now)
                                }
                            }
                            return positions
                        }
                    },
                    tooltip: {
                        xDateFormat: '%Y-%m-%d'
                    },
                    series: [{
                        name: 'rating',
                        data: [{{ data }}],
                        zones: [{
                            value: 1200,
                            color: '#808080'
                        }, {
                            value: 1400,
                            color: '#008000'
                        }, {
                            value: 1600,
                            color: '#03A89E'
                        }, {
                            value: 1900,
                            color: '#0000ff'
                        }, {
                            value: 2200,
                            color: '#a0a'
                        }, {
                            value: 2400,
                            color: '#FF8C00'
                        }, {
                            color: '#ff0000'
                        }]

                    }],

                    plotOptions: {
                        line: {
                            dataLabels: {
                                enabled: false
                            }
                        }
                    }
                });
            </script>
        </div>
    {% else %}
        <div class="my-5 pt-5 text-muted text-center">
            <a type="button" class="btn btn-primary  btn-lg" style="width: 30%"
               href="{% url 'login' %}?next={{ request.path }}">登录</a>
        </div>
        <div class="my-5 pt-5 text-muted text-center">
            <a type="button" class="btn btn-success  btn-lg" style="width: 30%; color: white"
               href="{% url 'logreg:register' %}">注册</a>
        </div>
    {% endif %}
{% endblock %}