admin/urls.py
from django.conf.urls import url
from django.urls import path
from .views import auto_update, index
app_name = 'admin'

urlpatterns = [
    url(r'^$', index.index),
    path(r'get_config', auto_update.get_config, name='get_config'),
    path(r'set_auto_update', auto_update.set_auto_update, name='set_auto_update'),
    url(r'finished', auto_update.finished),
    url(r'del_cf_users', index.del_cf_users),
    url(r'list_add', index.list_add),
    url(r'list_override', index.list_override),


]

logsystem/urls.py
from django.conf.urls import url, include
from django.urls import path
from logreg.views import index, send_captcha, user_check, user_exist, password_check, reset_password_captcha, receive_captcha
urlpatterns = [
    url(r'^board/', include('board.urls')),
    url(r'^logreg/', include('logreg.urls')),
    url(r'^logreg/', include('django.contrib.auth.urls')),
    url(r'^interfaces/', include('interfaces.urls')),
    url(r'^$', index, name='index'),
    url(r'^admin/', include('superuser.urls')),
    url(r'^ajax/send_captcha/', send_captcha, name='send_captcha'),
    url(r'^ajax/user_check', user_check, name='user_check'),
    url(r'^ajax/user_exist', user_exist, name='user_exist'),
    url(r'^ajax/password_check', password_check, name='password_check'),
    url(r'^ajax/reset_password_captcha/', reset_password_captcha),
    path('verify/<str:captcha>', receive_captcha),
]

superuser/urls.py
from django.conf.urls import url
from django.urls import path
from .views import auto_update, superuser_views

app_name = 'superuser'

urlpatterns = [
    path('', superuser_views.modify),
    path('get_config', auto_update.get_config, name='get_config'),
    path('set_auto_update', auto_update.set_auto_update, name='set_auto_update'),
    url(r'finished', auto_update.finished),
    path('board/create', superuser_views.create_board),
    path('handle_controller', superuser_views.list_user, name='handle_controller'),
    path('handle_delete', superuser_views.delete_handle),
    path('download_excel', superuser_views.excel_export, name='excel_export'),
    path('modify_handle', superuser_views.edit_handle),
    path('jump_modify_board/<int:board_id>', superuser_views.jump_modify_board),
    path('modify_board_board', superuser_views.modify_board_board),
    path('modify_board_modify_user', superuser_views.modify_board_modify_user),
    path('modify_board_del_user', superuser_views.modify_board_del_user),
    path('modify_board_add_user', superuser_views.modify_board_add_user),
    path('delete_board', superuser_views.delete_board),
    path('manual_update/<int:only_board>', auto_update.manual_update, name='manual_update')
]

superuser/models.py
from django.db import models

# Create your models here.

superuser/forms.py
from django import forms
from django.forms import DateTimeInput
import datetime


class StaticBoardForm(forms.Form):
    # class Meta:
    #     model = RatingChangeStaticBoard
    #     fields = ['name', 'start_time', 'end_time']
    #     labels = {
    #         'name': '名称',
    #         'start_time': '开始时间',
    #     }
    #     widgets = {
    #         'name': forms.TextInput(attrs={'class': 'form-control'}),
    #         'start_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}, format=['%Y-%m-%dT%H:%M']),
    #     }

    name = forms.CharField(label='名称', min_length=2, max_length=20,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    start_time = forms.DateTimeField(label='开始时间', widget=DateTimeInput(attrs={'type': 'datetime-local'}),
                                     input_formats=['%Y-%m-%dT%H:%M'])
    end_time = forms.DateTimeField(label='结束时间', widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
                                   input_formats=['%Y-%m-%dT%H:%M'])

    # type = forms.ChoiceField(label='类型',
    #                          widget=forms.Select(attrs={'class': 'form-control', 'disabled': 'disabled'}),
    #                          choices=(('static', '静态榜'), ('dynamic', '动态榜')), required=False)
    type = forms.ChoiceField(label='类型',
                             widget=forms.Select(attrs={'class': 'form-control'}),
                             choices=(
                                 ('rating', '分数榜'),
                                 ('rating_change', '升级榜'),
                                 ('max_three', '最高三场'),
                             ), required=False)

    list_text = forms.CharField(label='名单导入', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '15'}))

    def clean_start_time(self):
        start_time = self.cleaned_data.get('start_time')
        return start_time

    def clean_end_time(self):
        end_time = self.cleaned_data.get('end_time')
        start_time = self.cleaned_data.get('start_time')
        print(start_time, end_time)
        if start_time >= end_time:
            raise forms.ValidationError('结束时间不能在开始时间之前')
        return end_time



superuser/views/auto_update.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render
from board.auto_update import UpdateSetting
from superuser.tasks import update_alone


def set_auto_update(request):
    if not request.user.is_authenticated or request.user.is_superuser == 0:
        return HttpResponseRedirect('..')
    if 'hour' in request.GET.keys():
        get = request.GET.copy()
        get['is_open'] = True if get['is_open'] == 'true' else False
        UpdateSetting(is_open=get['is_open'], hour=get['hour'], minute=get['minute']).write_setting()
        return JsonResponse({})
    return render(request, 'superuser/auto_update/set_auto_update.html')


def get_config(request):
    if not request.user.is_authenticated or request.user.is_superuser == 0:
        return HttpResponseRedirect('..')
    setting = UpdateSetting()
    setting.load_setting()
    info = {'is_open': setting.is_open, 'hour': setting.hour, 'minute': setting.minute}
    return JsonResponse(info)


def finished(request):
    return render(request, 'superuser/auto_update/finished.html')


def manual_update_operate(only_board):
    update_alone.delay(only_board)


def manual_update(request, only_board=False):
    if request.user.is_authenticated and request.user.is_superuser:
        manual_update_operate(only_board)
    return redirect('/admin')

superuser/views/index.py
from django.shortcuts import render, redirect
from board.models import CFUser
import re
from board.utility import get_rating


def index(request):
    if not request.user.is_authenticated or request.user.is_superuser == 0:
        return redirect('/')
    return render(request, 'superuser/modify.html', {'users': CFUser.objects.all()})


def del_cf_users(request):
    if not request.user.is_authenticated or request.user.is_superuser == 0:
        return redirect('/')
    if request.method != 'POST':
        redirect('/')
    for handle in request.POST.getlist('users[]'):
        CFUser.objects.filter(handle=handle).get().delete()
    return render(request, 'superuser/modify.html', {'users': CFUser.objects.all()})


def _deal_list(text):  # not a view function
    results = []
    visit = []
    for line in text.split('\n'):
        line = line.strip()
        if len(line) == 0:
            continue
        res = get_user_info(line)
        res['text'] = line
        if res['status'] == 'OK':
            if res['handle'] in visit:
                res['comment'] = 'handle: ' + res['handle'] + '与上面重复'
            else:
                visit.append(res['handle'])
        results.append(res)
    return {'results': results, 'handles': visit}


def _update_cf_user(res): #not a view
    if res['status'] != 'OK':
        return
    if len(CFUser.objects.filter(handle=res['handle'])) == 0:
        CFUser.objects.create(handle=res['handle'], rating=res['rating'], realname=res['realname'])
    else:
        user = CFUser.objects.filter(handle=res['handle']).get()
        user.rating = res['rating']
        if res['realname']:
            user.realname = res['realname']
        user.save()


def list_add(request):
    if not request.user.is_authenticated or request.user.is_superuser == 0:
        return redirect('/')
    if request.method == 'POST':
        msg = _deal_list(request.POST['list'])
        for res in msg['results']:
            _update_cf_user(res)
        msg['results'].sort(key=lambda x: x['status'])
        return render(request, 'superuser/add_result.html', context=msg)
    return render(request, 'superuser/list_add.html')


def list_override(request):
    if not request.user.is_authenticated or request.user.is_superuser == 0:
        return redirect('/')
    if request.method == 'POST':
        msgs = _deal_list(request.POST['list'])
        handles = msgs['handles']
        deleted = []
        for user in CFUser.objects.all():
            if user.handle not in handles:
                res = {'status': 'OK', 'comment': '删除成功', 'handle': user.handle, 'realname': user.realname}
                msgs['results'].append(res)
                deleted.append(user.handle)
                user.delete()
        for res in msgs['results']:
            if res['status'] == 'OK' and res['handle'] not in deleted:
                _update_cf_user(res)
        return render(request, 'superuser/add_result.html', context=msgs)
    return render(request, 'superuser/list_override.html')


def get_user_info(line):
    handle = re.findall(re.compile(r'[0-9a-zA-Z_]{3,24}'), line)
    realname = re.findall(re.compile(r'[\u4e00-\u9fa5]{2,3}'), line)
    if len(handle) == 0 or len(handle) > 1 or len(realname) > 1:
        return {'status': 'FAILED', 'comment': '无法识别'}
    if len(realname) == 0:
        realname.append('')
    handle = handle[0].lower()
    res = {'realname': realname[0], 'handle': handle}
    if len(CFUser.objects.filter(handle=handle)) != 0:
        res['rating'] = CFUser.objects.filter(handle=handle).get().rating
        res['status'] = 'OK'
        return res
    res.update(get_rating(handle[0]))
    return res

superuser/templates/superuser/create_board.html
{% extends 'superuser/list_tab.html' %}
{% load staticfiles %}
{% block js %}
{% endblock %}
{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-group">
            <label>名称</label>
            <input type="text" class="form-control" name="name" value="{{ initial.name }}">
            {{ errors.name }}
            <label>类型</label>
            <select class="form-control" disabled="disabled">
                <option>静态榜</option>
                <option>动态榜</option>
            </select>
            开始时间：<input type="datetime-local" name="start_time" value="{{ initial.start_time }}">
            {{ errors.start_time }}
            截止时间：<input type="datetime-local" name="end_time" value="{{ initial.end_time }}">
            {{ errors.end_time }}
            <br/>
            <label>名单导入</label>
            <textarea class="form-control" rows="15" name="list_text" >{{ initial.list_text }}</textarea>
        </div>
        <table class="table">
            <tbody>
            <td align="center" style="border:0px;">
                <button class="btn btn-primary" id="btn_create" type="submit">创建</button>
            </td>
            </tbody>
        </table>
    </form>
{% endblock %}

superuser/templates/superuser/create_board_form.html
{% extends 'superuser/list_tab.html' %}
{% load staticfiles %}
{% block js %}
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {% for field in form %}
                <div>
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
        </div>
        <table class="table">
            <tbody>
            <td align="center" style="border:0px;">
                <button class="btn btn-primary" id="btn_create" type="submit">创建</button>
            </td>
            </tbody>
        </table>
    </form>
{% endblock %}

superuser/templates/superuser/handle_controller.html
{% extends 'superuser/list_tab.html' %}
{% block js %}
    <script>
        $(document).ready(function () {
            $(".list-group-item").removeClass("active")
            $('#element5').addClass('active')
            $('.list-group-item').click(function () {
                window.location.href = $(this).attr('href')
            })
        })
    </script>
{% endblock %}
{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">名字</th>
            <th scope="col">ID</th>
            <th scope="col">CFID</th>
            <th scope="col">年级</th>
            <th scope="col">昵称</th>
            <th scope="col">管理员</th>
            <th scope="col" style="text-align: center">操作</th>
        </tr>
        </thead>
        <tbody>
        <form id="form", class="form-control", method="post">
        {% csrf_token %}
        {% for user in users %}
            <tr class="element">
                <th scope="row"><input type="text" class="form-control" value="{{ user.realname }}"
                                       id="{{ user.id }}_realname"></th>
                <td><input type="text" class="form-control" value="{{ user.username }}" id="{{ user.id }}_username">
                </td>
                <td><input type="text" class="form-control" value="{{ user.handle }}" id="{{ user.id }}_CFID"></td>
                <td><select id="{{ user.id }}_grade"></select></td>
                <td><input type="text" class="form-control" value="{{ user.nickname }}" id="{{ user.id }}_nickname">
                </td>
                {% if user.is_superuser %}
                    <td><input type="checkbox" class="form-control"  checked="checked" id="{{ user.id }}_super" style="zoom:2">
                    </td>
                {% else %}
                    <td><input type="checkbox" class="form-control"   id="{{ user.id }}_super" style="zoom:2">
                    </td>
                {% endif %}
                <td align="center" style="border:0px;">
                    <button class="btn btn-primary" id="{{ user.id }}_save" type="button">修改</button>
                    <button class="btn btn-primary" id="{{ user.id }}_delete" type="button">删除</button>
                </td>
            </tr>
        {% endfor %}
        </form>
        </tbody>
    </table>
    <script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>
    <script>
        var date = new Date().getFullYear();
        date = date % 100;
        {% for user in users %}
            var grade = document.getElementById("{{ user.id }}_grade");
            for(var i = 1; i <= date; i++){
                if(i < 10)
                    grade.options.add(new Option('0' + i.toString(), i));
                else
                    grade.options.add(new Option(i.toString(), i));
            }
            $('#{{ user.id }}_grade').val({{ user.grade }});
        {% endfor %}
        {% for user in users %}
            $('#{{ user.id }}_super').prop("checked",);
            $("#{{ user.id }}_save").click(function () {
                var realname = $('#{{ user.id }}_realname').val();
                var username = $('#{{ user.id }}_username').val();
                var handle = $('#{{ user.id }}_CFID').val();
                var nickname = $('#{{ user.id }}_nickname').val();
                var superuser = $('#{{ user.id }}_super').prop("checked");
                var Grade = $("#{{ user.id }}_grade").val();
                $.ajax({
                    type: "POST",
                    url: "/admin/modify_handle",
                    data: {
                        "hand": handle,
                        "realname": realname,
                        "username": username,
                        "nickname": nickname,
                        'id':{{ user.id }},
                        'super':superuser,
                        'grade':Grade,
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                    },
                    success: function (ret) {
                        alert(ret.result);
                    }
                })
            })
            $("#{{ user.id }}_delete").click(function () {
                var con = window.confirm("确认删除" + $('#{{ user.id }}_realname').val() + '的账号吗？')
                if (con) {
                    $.ajax({
                        type: "POST",
                        url: "/admin/handle_delete",
                        data: {
                            'id':{{ user.id }},
                            csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                        },
                        success: function (ret) {
                            alert("删除成功！");
                        }
                    })
                }
            })
        {% endfor %}
    </script>
{% endblock %}

superuser/templates/superuser/import_result.html
{% extends 'superuser/list_tab.html' %}
{% load staticfiles %}
{% block js %}
    {{ block.super }}
    <script src="{% static '/superuser/modify.js' %}"></script>
{% endblock %}
{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">导入信息</th>
            <th scope="col">handle</th>
            <th scope="col">realname</th>
            <th scope="col">导入状态</th>
            <th scope="col">备注</th>
        </tr>
        </thead>
        <tbody>
        {% for info in results %}
            <tr>
                <th scope="row">{{ info.text }}</th>
                <td>{{ info.handle }}</td>
                <td>{{ info.realname }}</td>
                <td>{{ info.status }}</td>
                <td>{{ info.comment }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

superuser/templates/superuser/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block js %}
    <script>
        $(document).ready(function () {
            $('.nav-link').removeClass('active')
            $('#nav-element3').addClass('active')
        })
    </script>
{% endblock %}
{% block index %}
    {% csrf_token %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-2">
                <div class="list-group" id="list-tab" role="tablist">
                    <a class="list-group-item list-group-item-action active" data-toggle="list"
                       href="/admin" role="tab" aria-controls="home" id="element1">编辑排行榜名单</a>
                    <a class="list-group-item list-group-item-action" data-toggle="list"
                       href="/admin/list_add" role="tab" aria-controls="profile" id="element2">增加名单</a>
                    <a class="list-group-item list-group-item-action" data-toggle="list"
                       href="/admin/list_override" role="tab" aria-controls="messages" id="element3">覆盖名单</a>
                    <a class="list-group-item list-group-item-action" data-toggle="list"
                       href="/admin/set_auto_update" role="tab" aria-controls="messages" id="element4">设置自动更新</a>
                </div>
            </div>
            <div class="col">
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-2">
            </div>
        </div>
        {% block second_row %}
        {% endblock %}
    </div>
{% endblock %}

superuser/templates/superuser/list_tab.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block js %}
    <script>
        $(document).ready(function () {
            $('.nav-link').removeClass('active')
            $('#nav-element3').addClass('active')
        })
    </script>
{% endblock %}
{% block index %}
    {% csrf_token %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-2">
                <div class="list-group" id="list-tab" role="tablist">
                    <a class="list-group-item list-group-item-action active" data-toggle="list"
                       href="/admin" role="tab" aria-controls="home" id="element1">编辑排行榜</a>
                    <a class="list-group-item list-group-item-action" data-toggle="list"
                       href="{% url 'superuser:handle_controller' %}" role="tab" aria-controls="messages" id="element5">编辑用户</a>
                    <a class="list-group-item list-group-item-action" data-toggle="list"
                    href="/admin/set_auto_update" role="tab" aria-controls="messages" id="element2">设置自动更新</a>
                    <a class="list-group-item list-group-item-action" data-toggle="list"
                    href="{% url 'superuser:manual_update' 0 %}" role="tab" aria-controls="messages" id="element3">立即手动更新所有数据</a>
                    <a class="list-group-item list-group-item-action" data-toggle="list"
                    href="{% url 'superuser:manual_update' 1 %}" role="tab" aria-controls="messages" id="element4">立即手动更新榜单</a>
                    <a class="list-group-item list-group-item-action" data-toggle="list"
                    href="{% url 'superuser:excel_export' %}" role="tab" aria-controls="messages" id="element5">下载用户名单</a>
                </div>
            </div>
            <div class="col">
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-2">
            </div>
        </div>
    </div>
{% endblock %}

superuser/templates/superuser/modify.html
{% extends 'superuser/list_tab.html' %}
{% load staticfiles %}
{% block js %}
    {{ block.super }}
    <script src="{% static '/superuser/board_modify.js' %}"></script>
{% endblock %}
{% block content %}
    {% csrf_token %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">名称</th>
            <th scope="col">类型</th>
            <th scope="col">开始时间</th>
            <th scope="col">结束时间</th>
            <th scope="col">创建人</th>
        </tr>
        </thead>
        <tbody>
        {% for board in boards %}
            <tr class="element">
                <th scope="row">{{ board.id }}</th>
                <td>{{ board.name }}</td>
                <td>{{ board.type }}</td>
                <td>{{ board.start_time }}</td>
                <td>{{ board.end_time }}</td>
                <td>{{ board.creator }}</td>
                <td>
                    <button class="btn btn-primary" id="{{ board.id }}_modify">编辑</button>
                </td>
                <td>
                    <button class="btn btn-primary delete" id="board{{ board.id }}">删除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <table class="table">
        <tbody>
        <td align="center" style="border:0px;">
            <a class="btn btn-primary" href="board/create">创建新排行榜</a>
        </td>
        <td align="center" style="border:0px;">
            <button type="submit" class="btn btn-primary" id="btn_delete_all">删除所有标记项</button>
        </td>
        </tbody>
    </table>
    <script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>
    <script>
        {% for board in boards %}
            $('#{{ board.id }}_modify').click(function () {
              {#$.get({#}
              {#    type: "GET",#}
              {#    url: "/admin/jump_modify_board",#}
              {#    data: {#}
              {#        "id": {{ board.id }},#}
              {#        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()#}
              {#    }#}
              {# })#}
                window.open('/admin/jump_modify_board/{{ board.id }}')
            })
        {% endfor %}
    </script>
{% endblock %}